spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blog-api
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG